# Generated by Django 2.2.6 on 2019-11-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_size', models.PositiveSmallIntegerField()),
                ('result', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=100)),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
                ('age', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_set', models.CharField(max_length=500)),
                ('allowed_board_sizes', models.PositiveSmallIntegerField()),
                ('time_model', models.CharField(max_length=1000)),
                ('komi', models.FloatField()),
                ('handicap', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('notes', models.TextField()),
                ('result', models.FileField(upload_to='')),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_game', to='organizer.Games')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.Participants')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.RuleSet')),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='black_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to='organizer.Participants'),
        ),
        migrations.AddField(
            model_name='games',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_tournament', to='organizer.Tournament'),
        ),
        migrations.AddField(
            model_name='games',
            name='white_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='organizer.Participants'),
        ),
    ]
