# Generated by Django 2.2.6 on 2019-11-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
