# Generated by Django 4.0.6 on 2022-10-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_white', models.CharField(max_length=255)),
                ('opponent_black', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('handicap', models.CharField(max_length=255)),
            ],
        ),
    ]
