# Generated by Django 4.0.5 on 2022-06-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('hometown', models.CharField(max_length=255)),
                ('strength_number', models.IntegerField()),
                ('strength_type', models.CharField(max_length=1)),
                ('attending', models.BooleanField(default=False)),
            ],
        ),
    ]
